### PR TITLE
LPS 112393

### PR DESCRIPTION
**Pull request by diegonvs**
- LPS-112393 Increments the value of z-index for the resizing handle because the positioning changes for removing indentation made the resizing handle not being accessible
- LPS-112393 Hide the resize handle if the field isn't selected
- LPS-112393 Removes indentation for Form Group children

In addition to indentation, the behaviour of when we can resize a field has been changed

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:forms

**Comment by diegonvs** [comment]
ci:test:app-builder

**Comment by brunofariasdeo** [comment]
@diegonvs,
all the failures reported by ci:test:forms are not related to your changes in this pull request.

**Comment by diegonvs** [comment]
ci:forward

**Comment by diegonvs** [comment]
ci:forward

**Pull request closed without merging**
