### PR TITLE
LPS 113214

### PR DESCRIPTION
**Pull request by diegonvs**
I noticed that We're passing an incorrect value to `top` property value turning collapsible field groups not positioned correctly.

Also, a multiple repeatable button was being rendered because FieldBase was rendering a repeat button too. I passed a false value to FieldBase on repeatable props for preventing that. I fixed for just using the repeatable logic on FieldSet component, when this component is being rendered.

Commits:
- LPS-113214 Adjust CSS of Data Engine Layout Builder for working with Collapsible+Repeatable panels
- LPS-113214 Prevents rendering `repeatable`-like components of FieldBase on FieldSet

/cc @interaminense @kevenleone @brunobasto @matuzalemsteles

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:stop

**Comment by diegonvs** [comment]
ci:stop

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
LGTM

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:forward

**Pull request closed without merging**
