### PR TITLE
LPS 109939

### PR DESCRIPTION
**Pull request by diegonvs**

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:stop

**Comment by diegonvs** [comment]
ci:stop

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:forms

**Comment by diegonvs** [comment]
ci:test:app-builder

**Comment by diegonvs** [comment]
ci:test:forms

**Comment by diegonvs** [comment]
ci:test:app-builder

**Comment by diegonvs** [comment]
About the `ci:test:forms` results: 

* `LocalFile.FormRules#ViewPredefinedValueCanBeUsedToRequireAnotherField`: 
```
exec] com.liferay.poshi.runner.PoshiRunner > test[LocalFile.FormRules#ViewPredefinedValueCanBeUsedToRequireAnotherField] STANDARD_ERROR
     [exec]     java.lang.Exception: Element is not visible at "//button[contains(@class,'share-form-icon') and contains(@title,'Copy URL')]"
```

I didn't change this icon.

* `LocalFile.FormsDataProvider#ConfigureAutocompleteWithTextField`:

```
     [exec] com.liferay.poshi.runner.PoshiRunner > test[LocalFile.FormsDataProvider#ConfigureAutocompleteWithTextField] STANDARD_ERROR
     [exec]     java.lang.RuntimeException: Element is not present at "//input[@type='text' and contains(@id,'$url')] | //input[@type='text' and contains(@name,'$url')] | //div[contains(@class,'form-group')]//p[text()='${key_fieldLabel}'] | //div[contains(@data-field-name,'$url')]//div[contains(@class,'form-group')]//input"
```


* `LocalFile.FormsDataProvider#ConfigureAutocompleteWithTextField`:

```
     [exec] com.liferay.poshi.runner.PoshiRunner > test[LocalFile.Forms#DeleteSelectFromListOptionAndViewEntries] STANDARD_ERROR
     [exec]     java.lang.RuntimeException: Element is not present at "//div[contains(@class,'ddm-field-options-container')]//div[contains(@class,'ddm-field-options')][1]//input | //div[@class='options']//div[contains(@class,'form-field-container')][1]//input"
```

`.ddm-field-options` wasn't changed from my PR. Probably this selector was forgotten to being updated from DDM React migration.

* `Forms#DeleteSelectFromListOptionAndViewEntries`:

```
     [exec] com.liferay.poshi.runner.PoshiRunner > test[LocalFile.Forms#DeleteSelectFromListOptionAndViewEntries] STANDARD_ERROR
     [exec]     java.lang.RuntimeException: Element is not present at "//div[contains(@class,'ddm-field-options-container')]//div[contains(@class,'ddm-field-options')][1]//input | //div[@class='options']//div[contains(@class,'form-field-container')][1]//input"
     [exec]     	at com.liferay.poshi.runner.selenium.BaseWebDriverImpl.getWebElement(BaseWebDriverImpl.java:4280)
```

The same error as commented above.

* `FormRules#UseIsNotEmptyRuleToShowField`:

```
    [exec]
     [exec]     BUILD FAILED: Element is not present at "//a[contains(@class,'tab') and .='Basic'] | //a[contains(@aria-controls,'sidebarLightDetails')]//*[contains(text(),'Basic')]"
     [exec]     /Users/diegonascimento/workspace/liferay-portal/portal-web/test/functional/com/liferay/portalweb/macros/Form.macro[gotoAddField]:311
     [exec]     /Users/diegonascimento/workspace/liferay-portal/portal-web/test/functional/com/liferay/portalweb/macros/Form.macro[addTextField]:32
     [exec]     /Users/diegonascimento/workspace/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/FormRules.testcase[UseIsNotEmptyRuleToShowField]:729
```

Not related to FormBuilder/Renderer

* `Forms#SubmitFormWithRequiredCheckboxField`:

```
  [exec] com.liferay.poshi.runner.PoshiRunner > test[LocalFile.Forms#SubmitFormWithRequiredCheckboxField] STANDARD_ERROR
     [exec]     java.lang.Exception: Element is not present at "//a[contains(@class,'tab') and .='Basic'] | //a[contains(@aria-controls,'sidebarLightDetails')]//*[contains(text(),'Basic')]"
     [exec]     	at com.liferay.poshi.runner.selenium.BaseWebDriverImpl$Condition.assertTrue(BaseWebDriverImpl.java:4485)
     [exec]     	at com.liferay.poshi.runner.selenium.BaseWebDriverImpl$Condition.waitFor(BaseWebDriverImpl.java:4520)
     [exec]     	at com.liferay.poshi.runner.selenium.BaseWebDriverImpl.waitForElementPresent(BaseWebDriverImpl.java:3269)
```

Same as above.

/cc @brunobasto @cvanut @alexcandidos

**Comment by brunofariasdeo** [comment]
@diegonvs,
all the failures reported by ci:test:forms are not related to your changes in this pull request.

**Comment by diegonvs** [comment]
ci:forward

**Comment by diegonvs** [comment]
ci:forward

**Comment by diegonvs** [comment]
ci:forward

**Pull request closed without merging**
