### PR TITLE
LPS-114816 Adds showLabel as a setting on FieldSet settings

### PR DESCRIPTION
**Pull request by diegonvs**

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:forms

**Comment by diegonvs** [comment]
ci:test:app-builder

**Comment by diegonvs** [comment]
ci:stop

**Comment by diegonvs** [comment]
ci:stop

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:forms

**Comment by diegonvs** [comment]
ci:test:app-builder

**Comment by alexcandidos** [comment]
Hi @diegonvs , the failures on App Builder test suite are known issues as you can see here: https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1205118054.

**Comment by diegonvs** [comment]
Considering that Bruno(Forms QA) and @alexcandidos noticed that this errors on CI was occurring in the past, this fix is okay. I gonna ci:forward.

**Comment by diegonvs** [comment]
ci:forward

**Pull request closed without merging**
