### PR TITLE
Document Library DDM Field

### PR DESCRIPTION
**Pull request by diegonvs**

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:test:bundle

**Comment by diegonvs** [comment]
ci:test:echo-acceptance

**Comment by diegonvs** [comment]
ci:test:forms

**Comment by diegonvs** [comment]
ci:test:app-builder

**Comment by matuzalemsteles** [comment]
Resent https://github.com/matuzalemsteles/liferay-portal/pull/27

**Pull request closed without merging**
