### PR TITLE
LPS 113769 Removes unnecessary showLabel property to FieldSet

### PR DESCRIPTION
**Pull request by diegonvs**
* LPS-113769 Removes unnecessary `showLabel` property to FieldSet
* LPS-113769 When using FieldSet, don't display `ddm-empty` paragraph element since a Field Group can't be required or not. For solving this, was added a new property to FieldBase called `showFieldHeader` where disables/enables the paragraph placeholder on top that wraps Required and Tooltip functionality

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
@diegonvs I was thinking.. can't we reuse `showLabel` instead of having this new `showFieldHeader` prop that is only used in `Fieldset` but was added for the generic `FieldBase` component? The reason I ask is because if we keep adding field specific props to `FieldBase` it's gonna have 1k props real fast 😄

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:stop

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:stop

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:forms

**Comment by diegonvs** [comment]
ci:app-builder

**Comment by cvanut** [comment]
> ci:forms

Hey @diegonvs the correct is ci:test:forms

**Comment by diegonvs** [comment]
ci:test:forms

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:forms

**Comment by diegonvs** [comment]
ci:test:app-builder

**Pull request closed without merging**
