### PR TITLE
Select DDM Field

### PR DESCRIPTION
**Pull request by diegonvs**

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:forms

**Comment by diegonvs** [comment]
ci:test:app-builder

**Comment by john-co** [comment]
ci:test:echo-acceptance

**Comment by zhangyan0701** [comment]
ci:test:bundle

**Comment by zhangyan0701** [comment]
**echo-acceptance results:**
https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1076307430

[Unrelated] - LocalizationWithWebContentUI#AddWCWithTranslation.
                     Quarantined in [this commit](https://github.com/leoadb/liferay-portal/pull/763).

**Comment by zhangyan0701** [comment]
**App Builder results:**
https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1076330758

**Forms result:**
**Comparison:**
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1079766332&testrayRunIdA=1076312812&statusB=2

- [Test Fix] - Most failures of App Builder and Forms are because the locator of select field is changed.

Affect locators:
FormViewBuilder#SELECT_FIELD
Form#DATA_PROVIDER_OUTPUT_PARAMETER_TYPE_FIELD
FormFields#SELECT_FIELD

- [Related to old baseline] - Forms#SubmitFormWithCustomTextContainingValidation
No validation error message for required field.

**The select field now displays the arrow icon in it. But there is another UI issue, the select field doesn't have a blue border when click it. This not fails functional tests.**

**Comment by diegonvs** [comment]
> The select field now displays the arrow icon in it. But there is another UI issue, the select field doesn't have a blue border when click it. This not fails functional tests.

Gotcha, I'll fix it. Thanks @zhangyan0701 💖

**Comment by diegonvs** [comment]
ci:test:echo-acceptance

**Comment by diegonvs** [comment]
ci:test:app-builder

**Comment by diegonvs** [comment]
ci:test:forms

**Comment by zhangyan0701** [comment]
ci:test:bundle

**Comment by zhangyan0701** [comment]
Hi @diegonvs,

The select field still doesn't have a blue border, please see below gif. Could you take a look when you have time? 
The results of functional tests are same as before. 
select field no border

**Comment by diegonvs** [comment]
ci:test:forms

**Comment by diegonvs** [comment]
ci:test:app-builder

**Comment by diegonvs** [comment]
ci:test:bundle

**Comment by zhangyan0701** [comment]
**The blue border issue has been fixed, I tested on FF and the select field now has blue border when click it.**
select field has blue border

**App Server Results:**
https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1085882244

- No related and no Test Fix.

**Forms results:**
https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1085878859

- [Text Fix] - I already updated some locators, but one of them didn't work because it changed again, some tests could keep running, but some of them failed with new errors, there are more locators need to be updated.

Affect locators: 
- Form#DATA_PROVIDER_OUTPUT_PARAMETER_TYPE_FIELD_2
- FormFields#GRID_RADIO_OPTIONS
- FormFields#VALIDATION_ARGUMENT
- FormRules#RULE_BUILDER_CONDITION_FIELD
- FormRules#RULE_BUILDER_CONDITION_OPERATOR_FIELD
- FormRules#RULE_BUILDER_CONDITION_VALUE_TYPE_FIELD
- FormRules#RULE_BUILDER_ACTION_FIELD
- FormRules#RULE_BUILDER_ACTION_TARGET_FIELD
- FormRules#RULE_BUILDER_JUMP_TO_PAGE_ACTION_TARGET

I updated them in my own [pr](https://github.com/zhangyan0701/liferay-portal/pull/158), [this commit ](https://github.com/zhangyan0701/liferay-portal/pull/158/commits/8612c0ec2a858e652647a9d84f4d14087171cb15). And rerun ci test, hopefully there are no more test fixes.

- [Related] - LocalFile.Forms#SelectAndRemoveMultipleOptionsInSelectFromListField

The drop down list of multiple options select field disappears after selecting one option, so user needs to click the field again to make the list appear again. This issue was not found before because this test was failed by locator changing before, and didn't get to this step.
PR12

**Issue does't happen on master:**
master

**Comment by diegonvs** [comment]
> The drop down list of multiple options select field disappears after selecting one option, so user needs to click the field again to make the list appear again. This issue was not found before because this test was failed by locator changing before, and didn't get to this step.


Fixed!  79fd9d8

**Comment by diegonvs** [comment]
ci:test:bundle

**Comment by diegonvs** [comment]
ci:test:forms

**Comment by diegonvs** [comment]
ci:test:app-builder

**Comment by diegonvs** [comment]
ci:test:echo-acceptance

**Comment by john-co** [comment]
Hi @diegonvs can you include the "LPS-108484" prefix in Summer's test fix commits?

cc/ @zhangyan0701, let's include the ticket prefix for test fixes directly related to the commits

**Comment by zhangyan0701** [comment]
**Echo Acceptance Results:**
- No related.

**App Builder Results:**
**Comparation:**
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1088536190&testrayRunIdA=1087666878&testrayTeamId=865153919&statusB=2

- No related.

**Forms Results:**
**Comparation:**
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1088536312&testrayRunIdA=1087646333&testrayTeamId=863785155&statusB=2

- [Test Fix] - LocalFile.FormRules#ConfigureAutofillRule
 Updated locator FormRules#RULE_BUILDER_AUTOFILL_OUTPUT_FIELD in [commit](https://github.com/zhangyan0701/liferay-portal/pull/158/commits/816a8e0e12c42c4d7569618af3b2a03e8e5e8c78).

- [Flaky pass on local] - LocalFile.Forms#NavigateToCorrectForm
                                   - LocalFile.FormsJumpToPage#ViewRuleAfterLabelEdit

- [Related to old baseline] - LocalFile.Forms#SubmitFormWithCustomTextContainingValidation
  Validation function doesn't work, error message doesn't display and can submit successfully.

- [Related] - LocalFile.Forms#SelectAndRemoveMultipleOptionsInSelectFromListField
The selected multiple options don't display in entries table when view entries of form.
forms with select muti options field view entries

- [Related] - LocalFile.Forms#SubmitFormWithAllFieldTypesAndThreePages
 I am not very sure about this, the grid radio looks different, when hover mouse over it, the circle doesn't change to blue, and after selecting, the style is different. This is may also related to [brunobasto#1113](https://github.com/brunobasto/liferay-portal/pull/1113).

Is this an expected change? If it is, then this should be a test fix.
grid

**Comment by diegonvs** [comment]
> Hi @diegonvs can you include the "LPS-108484" prefix in Summer's test fix commits?

For sure!

**Comment by diegonvs** [comment]
> The selected multiple options don't display in entries table when view entries of form.

Now it's working, I made a regression when fixing the dropdown issue 🤦‍♂

**Comment by diegonvs** [comment]
> I am not very sure about this, the grid radio looks different, when hover mouse over it, the circle doesn't change to blue, and after selecting, the style is different. This is may also related to brunobasto#1113.

Yes, It's okay since we're using now Clay components :)

**Comment by diegonvs** [comment]
ci:test:bundle

**Comment by diegonvs** [comment]
ci:test:app-builder

**Comment by diegonvs** [comment]
ci:test:forms

**Comment by diegonvs** [comment]
ci:test:echo-acceptance

**Comment by matuzalemsteles** [comment]
hey guys, I added the corresponding Select commits to this PR https://github.com/matuzalemsteles/liferay-portal/pull/27, we will start testing them there once we have https://github.com/brunobasto/liferay-portal/pull/1113 on the master.

**Comment by john-co** [comment]
#### App Builder Results:
- [related] - js-unit test failure - https://issues.liferay.com/browse/LPS-111520 - Error:
```
     [exec] > Task :apps:dynamic-data-mapping:dynamic-data-mapping-form-builder:packageRunTest FAILED
     [exec] FAIL test/js/components/Sidebar/Sidebar.es.js (6.352s)
     [exec]   ??? Sidebar ??? Changing field type ??? keeps basic properties after changing field type
     [exec] 
     [exec]     expect(jest.fn()).toHaveBeenCalledWith(...expected)
     [exec] 
     [exec]     - Expected
     [exec]     + Received
     [exec] 
     [exec]       "focusedFieldEvaluationEnded",
     [exec]     @@ -17,30 +17,34 @@
     [exec]                   "columns": Array [
     [exec]                     Object {
     [exec]                       "fields": Array [
     [exec]                         Object {
     [exec]                           "fieldName": "label",
     [exec]     +                     "instanceId": "wwgnSwfF",
     [exec]                           "localizable": true,
     [exec]                           "localizedValue": Object {
     [exec]                             "en_US": "Text Field",
     [exec]                           },
     [exec]                           "type": "text",
     [exec]                           "value": "Text Field",
     [exec]                           "visible": true,
     [exec]                         },
     [exec]                         Object {
     [exec]                           "fieldName": "name",
     [exec]     +                     "instanceId": "qkE6APsh",
     [exec]                           "value": "TextField",
     [exec]                           "visible": true,
     [exec]                         },
     [exec]                         Object {
     [exec]                           "fieldName": "required",
     [exec]     +                     "instanceId": "SBkWSa8N",
     [exec]                           "value": true,
     [exec]                           "visible": true,
     [exec]                         },
     [exec]                         Object {
     [exec]                           "fieldName": "showLabel",
     [exec]     +                     "instanceId": "sujfcHc0",
     [exec]                           "value": true,
     [exec]                           "visible": false,
     [exec]                         },
     [exec]                       ],
     [exec]                     },,
     [exec] 
     [exec]     Number of calls: 1
     [exec] 
     [exec]       466 | 			};
     [exec]       467 | 
     [exec]     > 468 | 			expect(component.context.dispatch).toHaveBeenCalledWith(
     [exec]           | 			                                   ^
     [exec]       469 | 				'focusedFieldEvaluationEnded',
     [exec]       470 | 				changedFieldType
     [exec]       471 | 			);
     [exec] 
     [exec]       at Object.toHaveBeenCalledWith (test/js/components/Sidebar/Sidebar.es.js:468:39)
     [exec] 
     [exec]   ??? Sidebar ??? Changing field type ??? does not keep validation settings between field type
     [exec] 
     [exec]     expect(jest.fn()).toHaveBeenCalledWith(...expected)
     [exec] 
     [exec]     - Expected
     [exec]     + Received
     [exec] 
     [exec]       "focusedFieldEvaluationEnded",
     [exec]     @@ -17,30 +17,34 @@
     [exec]                   "columns": Array [
     [exec]                     Object {
     [exec]                       "fields": Array [
     [exec]                         Object {
     [exec]                           "fieldName": "label",
     [exec]     +                     "instanceId": "1usymdfl",
     [exec]                           "localizable": true,
     [exec]                           "localizedValue": Object {
     [exec]                             "en_US": "Text Field",
     [exec]                           },
     [exec]                           "type": "text",
     [exec]                           "value": "Text Field",
     [exec]                           "visible": true,
     [exec]                         },
     [exec]                         Object {
     [exec]                           "fieldName": "name",
     [exec]     +                     "instanceId": "0zmTZjLq",
     [exec]                           "value": "TextField",
     [exec]                           "visible": true,
     [exec]                         },
     [exec]                         Object {
     [exec]                           "fieldName": "required",
     [exec]     +                     "instanceId": "jcRr5qj6",
     [exec]                           "value": true,
     [exec]                           "visible": true,
     [exec]                         },
     [exec]                         Object {
     [exec]                           "fieldName": "showLabel",
     [exec]     +                     "instanceId": "mBlbaySH",
     [exec]                           "value": true,
     [exec]                           "visible": false,
     [exec]                         },
     [exec]                       ],
     [exec]                     },,
     [exec] 
     [exec]     Number of calls: 1
     [exec] 
     [exec]       533 | 				)
     [exec]       534 | 			).not.toEqual('a=b');
     [exec]     > 535 | 			expect(component.context.dispatch).toHaveBeenCalledWith(
     [exec]           | 			                                   ^
     [exec]       536 | 				'focusedFieldEvaluationEnded',
     [exec]       537 | 				changedFieldType
     [exec]       538 | 			);
     [exec] 
     [exec]       at Object.toHaveBeenCalledWith (test/js/components/Sidebar/Sidebar.es.js:535:39)
     [exec] 
     [exec] Test Suites: 1 failed, 11 passed, 12 total
     [exec] Tests:       2 failed, 79 passed, 81 total
     [exec] Snapshots:   19 passed, 19 total
     [exec] Time:        17.104s
     [exec] Ran all test suites.
```
- [not related] - /modules-semantic-versioning-jdk8 - looks like it's failing on upstream


I didn't get to investigate ci:test:forms results

**Comment by zhangyan0701** [comment]
Will start review the ci:test:forms results.

**Comment by zhangyan0701** [comment]
**Forms Results:**
**Comparison:**
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1088536312&testrayRunIdA=1090497651&testrayTeamId=863785155&statusB=2

- [Test Fix] - LocalFile.FormRules#ConfigureAutofillRule
  I updated this locator in commit https://github.com/zhangyan0701/liferay-portal/pull/158/commits/816a8e0e12c42c4d7569618af3b2a03e8e5e8c78. If you want to fix it in this pr, please cherry pick this commit.

- [Test Fix] - LocalFile.Forms#SubmitFormWithAllFieldTypesAndThreePages
  This is maybe actually related to [brunobasto#1113](https://github.com/brunobasto/liferay-portal/pull/1113), but I already updated the locator FormFields#GRID_RADIO_OPTIONS in this pr together with the Select field locators. We also need to change the click function when click grid radio, like this change https://github.com/zhangyan0701/liferay-portal/pull/158/commits/16c1779e8c6fba1637b00eb4fbb184fdf71f0991. 

- [Related] - LocalFile.Forms#SubmitFormWithCustomTextContainingValidation
 I thought this was related to [brunobasto#1113](https://github.com/brunobasto/liferay-portal/pull/1113), but I checked the results of that pr that this test was passing there. 
Can you also take a look at this one? Which pr may caused this and in which pr will fix this?

**Validation function doesn't work, error message doesn't display and can submit successfully.**
validation error

- [Related] - LocalFile.FormsDataProvider#ConfigureWithSelectField - LocalFile.FormsDataProvider#ViewDataRetrievedForGuestUser

**The corresponding options don't display after changing Create List of Select from List field:**
create list

**Comment by diegonvs** [comment]
Hey @zhangyan0701, @john-co, 
>Test Fix] - LocalFile.FormRules#ConfigureAutofillRule
I updated this locator in commit zhangyan0701@816a8e0. If you want to fix it in this pr, please cherry pick this commit.

> [Test Fix] - LocalFile.Forms#SubmitFormWithAllFieldTypesAndThreePages
This is maybe actually related to brunobasto#1113, but I already updated the locator FormFields#GRID_RADIO_OPTIONS in this pr together with the Select field locators. We also need to change the click function when click grid radio, like this change zhangyan0701@16c1779.

@matuzalemsteles will cherry-pick these commits into the [PR](https://github.com/brunobasto/liferay-portal/pull/1113) of part 1, right?

**Comment by diegonvs** [comment]
> [related] - js-unit test failure - https://issues.liferay.com/browse/LPS-111520 

Matu fixed on the https://github.com/brunobasto/liferay-portal/pull/1113, I'll rebase and check

**Comment by diegonvs** [comment]
Hey @zhangyan0701, I'm not able to reproduce it in both PRs(this one and brunobasto#1113)

**Comment by zhangyan0701** [comment]
ci:test:bundle

**Comment by zhangyan0701** [comment]
ci:test:forms

**Comment by zhangyan0701** [comment]
Hi @diegonvs, I rerun ci:test:forms and will check the results to see if the issue is reproducible.

**Comment by zhangyan0701** [comment]
Hi @diegonvs, there is rebase error, so I built a bundle on local and tested the issues.

- **Issue1 "The corresponding options don't display after changing Create List of Select from List field"  no longer reproduced, and I didn't see it in [brunobasto#1113](https://github.com/brunobasto/liferay-portal/pull/1113/) neither.**

- **Issue2 "Validation function" still can be reproduced. And the real problem is that the validation option will change to "Contains" after saving no matter which option you select.**

Affect test: LocalFile.FormsDataProvider#ConfigureWithSelectField

validation

**Comment by diegonvs** [comment]
> Issue2 "Validation function" still can be reproduced. And the real problem is that the validation option will change to "Contains" after saving no matter which option you select.

Is fixed by cc8366b

**Comment by diegonvs** [comment]
ci:test:bundle

**Comment by diegonvs** [comment]
ci:test:app-builder

**Comment by diegonvs** [comment]
ci:test:forms

**Comment by diegonvs** [comment]
LocalFile.FormsDataProvider#ConfigureWithSelectField: 
```
...
   [delete] Deleting: /Users/diegonascimento/workspace/liferay-portal/null1591691662.properties

clean-up-mobile-device:
   [delete] Deleting: /Users/diegonascimento/workspace/liferay-portal/null1591691662.properties

clean-up-selenium-driver:
     [exec] No matching processes belonging to you were found
     [exec] Result: 1

BUILD SUCCESSFUL
Total time: 6 minutes 15 seconds
```

**Comment by diegonvs** [comment]
ci:test:bundle

**Comment by diegonvs** [comment]
ci:test:forms

**Comment by diegonvs** [comment]
ci:test:app-builder

**Comment by diegonvs** [comment]
ci:test:forms

**Comment by zhangyan0701** [comment]
**Forms failure:**
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1096390055&testrayRunIdA=1097090730&testrayTeamId=863785155&statusB=2

- [Related] - LocalFile.Forms#SubmitFormWithCustomTextContainingValidation
  https://issues.liferay.com/browse/LPS-111668 still occurs, when add a new field and select a validation option such as "Does not Contains", then save form, the option changed to "Contains”, but now if I edit field by selecting "Does not Contains" again, then save form again, the option can be saved. Before the fix, edit didn't work neither.

**Comment by diegonvs** [comment]
> [Related] - LocalFile.Forms#SubmitFormWithCustomTextContainingValidation
https://issues.liferay.com/browse/LPS-111668 still occurs, when add a new field and select a validation option such as "Does not Contains", then save form, the option changed to "Contains”, but now if I edit field by selecting "Does not Contains" again, then save form again, the option can be saved. Before the fix, edit didn't work neither.

Hey @zhangyan0701, @matuzalemsteles cherry-picked my work on Select field to [Part 2 PR](https://github.com/matuzalemsteles/liferay-portal/pull/27) and with his commits on Validation field, everything is running well.

@john-co, @zhangyan0701 I'll close this PR in favor of https://github.com/matuzalemsteles/liferay-portal/pull/27

**Pull request closed without merging**
